#disk-image-create -a $ARCH -o $IMAGE_NAME -t $TYPE --image-cache ~/.cache/image-create -p $PACKAGES $BASE_ELEMENTS $AGENT_ELEMENTS $DEPLOYMENT_BASE_ELEMENTS $DEPLOYMENT_TOOL
disk-image-create -a $ARCH -o $IMAGE_NAME -t $TYPE -p $PACKAGES $BASE_ELEMENTS $AGENT_ELEMENTS $DEPLOYMENT_BASE_ELEMENTS $DEPLOYMENT_TOOL
